2023-03-27 18:12:41,468:logging_decorator:ERROR:Exception in fetch_blog: You are not allowed to view blog with id='private-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/version3/logging_decorator.py"', ' line 81', ' in wrapper_log_exceptions\n    return func(*args']
2023-03-27 18:12:49,032:logging_decorator:ERROR:Exception in fetch_blog: You are not allowed to view blog with id='private-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/version3/logging_decorator.py"', ' line 81', ' in wrapper_log_exceptions\n    return func(*args']
2023-03-27 18:12:51,040:logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='wrong-blog'                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/version3/logging_decorator.py"', ' line 81', ' in wrapper_log_exceptions\n    return func(*args']
2023-04-04 16:07:25,366:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='first-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
2023-04-04 16:07:41,936:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='first-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
2023-04-04 16:07:44,273:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='first-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
2023-04-04 16:07:46,537:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='wrong-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
2023-04-04 16:07:53,779:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='wrong-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
2023-04-04 16:07:58,708:utils.logging_decorator:ERROR:Exception in fetch_blog: Unable to find blog with id='private-blog'.                                
['Traceback (most recent call last):\n  File "/Users/benkaan/Desktop/projects/api_exception_handling/versions/v3/db.py"', ' line 59', ' in fetch_blog\n    cur.execute(f"SELECT * FROM blogs WHERE id=\'{id}\'")\nsqlite3.OperationalError: no such table: blogs\n\nDuring handling of the above exception']
